services:
  postgres-invoice-service:
    image: postgres:15.0
    container_name: postgres-invoice-service
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=invoice-service
    networks:
      - nginx-proxy-manager
      - redpanda_network
      - keycloak

  invoice-service:
    container_name: invoice-service
    build:
      context: .
    ports:
      - 8089:8089
    depends_on:
      - postgres-invoice-service
    networks:
      - nginx-proxy-manager
      - redpanda_network
      - keycloak

networks:
  nginx-proxy-manager:
    external: true
  redpanda_network:
    external: true
  keycloak:
    external: true

