services:
  postgres-invoiceservice:
    image: postgres:15.0
    container_name: postgres-invoiceservice
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=invoiceservice
  invoiceservice:
    container_name: invoiceservice
    build:
      context: .
    ports:
      - 8084:8080
    depends_on:
      - postgres-invoiceservice
